/// Independent Phase-B QA reference for Nursery simple phonics evidence.
///
/// This deliberately does not mirror JSON flags mechanically. It is a curated
/// guardrail so content drift can be detected by tests and simulator tools.
const Map<String, Set<String>> nurserySimplePhonicsWords =
    <String, Set<String>>{
  'A': <String>{
    'Apple',
    'Ant',
    'Axe',
    'Avocado',
    'Alligator',
    'Ambulance',
    'Arrow'
  },
  'B': <String>{
    'Ball',
    'Banana',
    'Bird',
    'Bus',
    'Boat',
    'Book',
    'Butterfly',
    'Balloon'
  },
  'C': <String>{'Cat', 'Car', 'Cup', 'Cow', 'Cake', 'Cap', 'Candle', 'Carrot'},
  'D': <String>{'Dog', 'Duck', 'Doll', 'Door', 'Deer', 'Dice', 'Donut'},
  'E': <String>{'Egg', 'Elephant', 'Engine'},
  'F': <String>{'Fish', 'Fox', 'Feather', 'Foot', 'Fan'},
  'G': <String>{'Goat', 'Gift', 'Girl', 'Guitar', 'Goose'},
  'H': <String>{
    'Hat',
    'Hen',
    'House',
    'Horse',
    'Hand',
    'Heart',
    'Helicopter',
    'Hammer'
  },
  'I': <String>{'Ink', 'Insect', 'Igloo', 'Iguana'},
  'J': <String>{
    'Jug',
    'Juice',
    'Jet',
    'Jar',
    'Jeans',
    'Jacket',
    'Jeep',
    'Jewel'
  },
  'K': <String>{
    'Kite',
    'Key',
    'King',
    'Kangaroo',
    'Kiwi',
    'Koala',
    'Kettle',
    'Keyboard'
  },
  'L': <String>{
    'Lion',
    'Leaf',
    'Lemon',
    'Lamp',
    'Ladder',
    'Ladybug',
    'Lock',
    'Lotus'
  },
  'M': <String>{
    'Mango',
    'Moon',
    'Mouse',
    'Monkey',
    'Milk',
    'Mirror',
    'Mountain',
    'Mug'
  },
  'N': <String>{
    'Nest',
    'Nose',
    'Nut',
    'Net',
    'Newspaper',
    'Nurse',
    'Necklace',
    'Notebook'
  },
  'O': <String>{'Ox', 'Octopus', 'Ostrich'},
  'P': <String>{
    'Pen',
    'Pig',
    'Pear',
    'Parrot',
    'Pizza',
    'Panda',
    'Peacock',
    'Pumpkin'
  },
  'Q': <String>{},
  'R': <String>{
    'Rabbit',
    'Rose',
    'Rain',
    'Ring',
    'Robot',
    'Rocket',
    'Rainbow',
    'Rooster'
  },
  'S': <String>{'Sun', 'Socks', 'Scissors'},
  'T': <String>{'Tiger', 'Tomato', 'Toothbrush', 'Turtle', 'Teddy'},
  'U': <String>{'Umbrella', 'Up', 'Under'},
  'V': <String>{
    'Van',
    'Violin',
    'Vegetable',
    'Vase',
    'Volcano',
    'Vest',
    'Vacuum',
    'Vulture'
  },
  'W': <String>{
    'Watch',
    'Water',
    'Whale',
    'Window',
    'Watermelon',
    'Wheel',
    'Worm',
    'Wagon'
  },
  'X': <String>{},
  'Y': <String>{
    'Yak',
    'Yellow',
    'Yo-yo',
    'Yacht',
    'Yarn',
    'Yogurt',
    'Yolk',
    'Yam'
  },
  'Z': <String>{
    'Zebra',
    'Zero',
    'Zoo',
    'Zip',
    'Zucchini',
    'Zigzag',
    'Zeppelin',
    'Zoom'
  },
};

const Map<String, String> nurseryAdvancedPhonicsReason = <String, String>{
  'Aeroplane': 'different A vowel sound',
  'Envelope': 'accent-sensitive opening vowel',
  'Earth': 'not the simple short-E sound',
  'Eagle': 'long-E sound',
  'Eye': 'spelling begins E but spoken word begins like the letter name I',
  'Ear': 'not the simple short-E sound',
  'Drum': 'initial consonant cluster',
  'Frog': 'initial consonant cluster',
  'Flower': 'initial consonant cluster',
  'Flag': 'initial consonant cluster',
  'Grapes': 'initial consonant cluster',
  'Glass': 'initial consonant cluster',
  'Globe': 'initial consonant cluster',
  'Ice Cream': 'long-I sound',
  'Island': 'long-I sound',
  'Ice Cube': 'long-I sound',
  'Ivy': 'long-I sound',
  'Orange': 'accent-sensitive vowel',
  'Owl': 'different O vowel sound',
  'Onion': 'different O vowel sound',
  'Olive': 'accent-sensitive vowel',
  'Ocean': 'long-O sound',
  'Queen': 'Q + U pattern is not treated as one simple consonant sound',
  'Question': 'Q + U pattern is not treated as one simple consonant sound',
  'Quilt': 'Q + U pattern is not treated as one simple consonant sound',
  'Quail': 'Q + U pattern is not treated as one simple consonant sound',
  'Quill': 'Q + U pattern is not treated as one simple consonant sound',
  'Quarter': 'Q + U pattern is not treated as one simple consonant sound',
  'Quiver': 'Q + U pattern is not treated as one simple consonant sound',
  'Quiet': 'Q + U pattern is not treated as one simple consonant sound',
  'Star': 'initial consonant cluster',
  'Snake': 'initial consonant cluster',
  'Ship': 'S + H digraph changes the sound',
  'Spoon': 'initial consonant cluster',
  'Strawberry': 'initial consonant cluster',
  'Tree': 'initial consonant cluster',
  'Train': 'initial consonant cluster',
  'Truck': 'initial consonant cluster',
  'Unicorn': 'long-U / letter-name onset',
  'Uniform': 'long-U / letter-name onset',
  'Utensils': 'long-U onset',
  'Urn': 'not the simple short-U sound',
  'Ukulele': 'not used for simple short-U practice',
  'X-ray': 'letter-name X onset, not a simple /ks/ beginning',
  'Xylophone': 'initial X is pronounced like Z',
  'Box': 'X is not at the beginning',
  'Fox': 'X is not at the beginning',
  'Ox': 'X is not at the beginning',
  'Wax': 'X is not at the beginning',
  'Six': 'X is not at the beginning',
  'Taxi': 'X is medial, not a beginning sound',
};

bool nurseryWordIsSimplePhonicsEligible(String letter, String word) =>
    nurserySimplePhonicsWords[letter]?.contains(word) ?? false;
