/// Frozen independently reviewed Phase-E references for legacy Class 3–5 content.
/// These are intentionally separate from the JSON payloads to catch later drift.
const Map<String, Object> phaseELegacyFactAnswers = <String, Object>{
  'c3_map_quest_map3_1': 'East',
  'c3_map_quest_map3_2': 'North',
  'c3_map_quest_map3_3': 'Library',
  'c3_map_quest_map3_4': 'Represent a place or feature',
  'c3_map_quest_map3_5': 'East',
  'c3_map_quest_map3_6': 'Legend or key',
  'c3_science_lab_q01': 'Roots',
  'c3_science_lab_q02': 'Wood',
  'c3_science_lab_q03': 'Solid',
  'c3_science_lab_q04': 'Flower',
  'c3_science_lab_q05': 'It melts into water',
  'c3_science_lab_q06': 'Cotton cloth',
  'c3_science_lab_q07': 'To help make food',
  'c3_science_lab_q08': 'Condensation',
  'c3_science_lab_q09': 'It is transparent',
  'c4_map_quest_map4_1': 'Odisha',
  'c4_map_quest_map4_2': 'Rajasthan',
  'c4_map_quest_map4_3': 'Yamuna',
  'c4_map_quest_map4_4': 'Tamil Nadu',
  'c4_map_quest_map4_5': 'East',
  'c4_map_quest_map4_6': 'Western Ghats',
  'c4_science_lab_q01': 'Wood',
  'c4_science_lab_q02': 'Solid',
  'c4_science_lab_q03': 'Roots',
  'c4_science_lab_q04': 'Iron',
  'c4_science_lab_q05': 'It becomes solid ice',
  'c4_science_lab_q06': 'Carbon dioxide',
  'c4_science_lab_q07': 'Poles',
  'c4_science_lab_q08': 'Water vapour',
  'c4_science_lab_q09': 'Change one factor and keep others the same',
  'c5_map_quest_map5_1': 'Himalayas',
  'c5_map_quest_map5_2': 'Indian Ocean',
  'c5_map_quest_map5_3': 'East',
  'c5_map_quest_map5_4': 'Ganga',
  'c5_map_quest_map5_5': 'Peninsular India',
  'c5_map_quest_map5_6': 'They compare map distance with real distance',
  'c5_science_lab_q01': 'Heart',
  'c5_science_lab_q02': 'Gas',
  'c5_science_lab_q03': 'Iron',
  'c5_science_lab_q04': 'Melting ice',
  'c5_science_lab_q05': 'Carbon dioxide',
  'c5_science_lab_q06': 'Pulley',
  'c5_science_lab_q07': 'The Sun appears at different angles',
  'c5_science_lab_q08': 'Circulatory system',
  'c5_science_lab_q09': 'A chemical change',
};

const Map<String, String> phaseEGrammarSentences = <String, String>{
  'c3_grammar_puzzle_grammar3_1': 'The brave dog runs.',
  'c3_grammar_puzzle_grammar3_2': 'A bright star shines.',
  'c3_grammar_puzzle_grammar3_3': 'The noisy train moves.',
  'c3_grammar_puzzle_grammar3_4': 'The clever fox jumps.',
  'c3_grammar_puzzle_grammar3_5': 'A gentle breeze blows.',
  'c3_grammar_puzzle_grammar3_6': 'The colourful butterfly flutters.',
  'c4_grammar_puzzle_grammar4_1': 'The brave dragon flies.',
  'c4_grammar_puzzle_grammar4_2': 'The clever fox jumps.',
  'c4_grammar_puzzle_grammar4_3': 'The noisy train moves.',
  'c4_grammar_puzzle_grammar4_4': 'The curious student carefully observes.',
  'c4_grammar_puzzle_grammar4_5': 'A powerful river rushes.',
  'c4_grammar_puzzle_grammar4_6': 'The patient gardener waits.',
  'c5_grammar_puzzle_grammar5_1': 'The curious student observes.',
  'c5_grammar_puzzle_grammar5_2': 'A powerful river flows.',
  'c5_grammar_puzzle_grammar5_3': 'The ancient monument stands.',
  'c5_grammar_puzzle_grammar5_4': 'The careful scientist observes.',
  'c5_grammar_puzzle_grammar5_5': 'The enormous telescope rotates.',
  'c5_grammar_puzzle_grammar5_6': 'A determined athlete trains.',
};

const Map<String, List<String>> phaseEScienceReactionIngredients =
    <String, List<String>>{
  'c3_science_lab_reaction_dissolve': <String>['Water', 'Salt'],
  'c3_science_lab_reaction_fizz': <String>['Baking Soda', 'Vinegar'],
  'c3_science_lab_reaction_none': <String>[],
  'c4_science_lab_reaction_dissolve': <String>['Water', 'Salt'],
  'c4_science_lab_reaction_fizz': <String>['Baking Soda', 'Vinegar'],
  'c4_science_lab_reaction_none': <String>[],
  'c5_science_lab_reaction_dissolve': <String>['Water', 'Salt'],
  'c5_science_lab_reaction_fizz': <String>['Baking Soda', 'Vinegar'],
  'c5_science_lab_reaction_none': <String>[],
};
