import 'dart:convert';
import 'dart:io';

class _Patch {
  const _Patch({
    required this.path,
    required this.label,
    required this.oldBase64,
    required this.newBase64,
  });

  final String path;
  final String label;
  final String oldBase64;
  final String newBase64;

  String get oldText => utf8.decode(base64.decode(oldBase64));
  String get newText => utf8.decode(base64.decode(newBase64));
}

String _normalize(String value) =>
    value.replaceAll('\r\n', '\n').replaceAll('\r', '\n');

int _occurrences(String haystack, String needle) {
  if (needle.isEmpty) return 0;
  var count = 0;
  var offset = 0;
  while (true) {
    final index = haystack.indexOf(needle, offset);
    if (index < 0) return count;
    count += 1;
    offset = index + needle.length;
  }
}

void main() {
  final root = Directory.current;
  final files = <String, String>{};

  for (final path in _patches.map((patch) => patch.path).toSet()) {
    final file = File('${root.path}${Platform.pathSeparator}'
        '${path.replaceAll('/', Platform.pathSeparator)}');
    if (!file.existsSync()) {
      stderr.writeln('Missing required file: $path');
      exitCode = 2;
      return;
    }
    files[path] = _normalize(file.readAsStringSync(encoding: utf8));
  }

  final applied = <String>[];
  final alreadyApplied = <String>[];

  // Validate and stage every patch in memory. Nothing is written until all
  // 30 contracts have been checked successfully.
  for (final patch in _patches) {
    var text = files[patch.path]!;
    final oldText = _normalize(patch.oldText).trimRight();
    final newText = _normalize(patch.newText).trimRight();

    if (text.contains(newText)) {
      alreadyApplied.add(patch.label);
      stdout.writeln('Already applied: ${patch.label}');
      continue;
    }

    final count = _occurrences(text, oldText);
    if (count != 1) {
      stderr.writeln(
        "Cannot apply '${patch.label}': expected old block exactly once, "
        'found $count. No production files were written.',
      );
      exitCode = 3;
      return;
    }

    text = text.replaceFirst(oldText, newText);
    files[patch.path] = text;
    applied.add(patch.label);
    stdout.writeln('Prepared: ${patch.label}');
  }

  for (final entry in files.entries) {
    final file = File('${root.path}${Platform.pathSeparator}'
        '${entry.key.replaceAll('/', Platform.pathSeparator)}');
    file.writeAsStringSync(entry.value, encoding: utf8, flush: true);
  }

  stdout.writeln('');
  stdout.writeln('Phase 7+8 UTF-8 production patch applied successfully.');
  stdout.writeln('Prepared changes: ${applied.length}');
  stdout.writeln('Already present: ${alreadyApplied.length}');
  stdout.writeln('Production files written: ${files.length}');
  stdout.writeln('');
  stdout.writeln('Next: dart format lib test');
  stdout.writeln('Then: flutter analyze');
}

const _patches = <_Patch>[
  _Patch(
    path: "lib/core/models/progress_models.dart",
    label: "progress_models import LearnerStage",
    oldBase64: "aW1wb3J0ICcuLi9udXJzZXJ5L251cnNlcnlfbGVhcm5pbmdfbW9kZWxzLmRhcnQnOw==",
    newBase64: "aW1wb3J0ICcuLi9udXJzZXJ5L251cnNlcnlfbGVhcm5pbmdfbW9kZWxzLmRhcnQnOwppbXBvcnQgJ2xlYXJuZXJfc3RhZ2UuZGFydCc7",
  ),
  _Patch(
    path: "lib/core/models/progress_models.dart",
    label: "ChildProfileSnapshot constructor learnerStage",
    oldBase64: "ICAgIHRoaXMuYXZhdGFyRW1vamkgPSAn8J+nkicsCiAgICB0aGlzLnNlbGVjdGVkQ2xhc3MgPSA0LA==",
    newBase64: "ICAgIHRoaXMuYXZhdGFyRW1vamkgPSAn8J+nkicsCiAgICB0aGlzLmxlYXJuZXJTdGFnZSA9IExlYXJuZXJTdGFnZS5zY2hvb2wsCiAgICB0aGlzLnNlbGVjdGVkQ2xhc3MgPSA0LA==",
  ),
  _Patch(
    path: "lib/core/models/progress_models.dart",
    label: "ChildProfileSnapshot learnerStage field",
    oldBase64: "ICBTdHJpbmcgaWQ7CiAgU3RyaW5nIG5hbWU7CiAgU3RyaW5nIGF2YXRhckVtb2ppOwogIGludCBzZWxlY3RlZENsYXNzOw==",
    newBase64: "ICBTdHJpbmcgaWQ7CiAgU3RyaW5nIG5hbWU7CiAgU3RyaW5nIGF2YXRhckVtb2ppOwogIExlYXJuZXJTdGFnZSBsZWFybmVyU3RhZ2U7CiAgaW50IHNlbGVjdGVkQ2xhc3M7",
  ),
  _Patch(
    path: "lib/core/models/progress_models.dart",
    label: "ChildProfileSnapshot learnerStage serialization",
    oldBase64: "ICAgICAgICAnYXZhdGFyRW1vamknOiBhdmF0YXJFbW9qaSwKICAgICAgICAnc2VsZWN0ZWRDbGFzcyc6IHNlbGVjdGVkQ2xhc3Ms",
    newBase64: "ICAgICAgICAnYXZhdGFyRW1vamknOiBhdmF0YXJFbW9qaSwKICAgICAgICAnbGVhcm5lclN0YWdlJzogbGVhcm5lclN0YWdlLm5hbWUsCiAgICAgICAgJ3NlbGVjdGVkQ2xhc3MnOiBzZWxlY3RlZENsYXNzLA==",
  ),
  _Patch(
    path: "lib/core/models/progress_models.dart",
    label: "ChildProfileSnapshot learnerStage migration",
    oldBase64: "ICAgICAgYXZhdGFyRW1vamk6IGpzb25bJ2F2YXRhckVtb2ppJ10gYXMgU3RyaW5nPyA/PyAn8J+nkicsCiAgICAgIHNlbGVjdGVkQ2xhc3M6IChqc29uWydzZWxlY3RlZENsYXNzJ10gYXMgbnVtPyk/LnRvSW50KCkgPz8gNCw=",
    newBase64: "ICAgICAgYXZhdGFyRW1vamk6IGpzb25bJ2F2YXRhckVtb2ppJ10gYXMgU3RyaW5nPyA/PyAn8J+nkicsCiAgICAgIGxlYXJuZXJTdGFnZTogbGVhcm5lclN0YWdlRnJvbVN0b3JhZ2UoanNvblsnbGVhcm5lclN0YWdlJ10pLAogICAgICBzZWxlY3RlZENsYXNzOiAoanNvblsnc2VsZWN0ZWRDbGFzcyddIGFzIG51bT8pPy50b0ludCgpID8/IDQs",
  ),
  _Patch(
    path: "lib/core/state/game_controller.dart",
    label: "GameController LearnerStage import",
    oldBase64: "aW1wb3J0ICcuLi9tb2RlbHMvZ2FtZV9tb2RlbHMuZGFydCc7CmltcG9ydCAnLi4vbW9kZWxzL3Byb2dyZXNzX21vZGVscy5kYXJ0Jzs=",
    newBase64: "aW1wb3J0ICcuLi9tb2RlbHMvZ2FtZV9tb2RlbHMuZGFydCc7CmltcG9ydCAnLi4vbW9kZWxzL2xlYXJuZXJfc3RhZ2UuZGFydCc7CmltcG9ydCAnLi4vbW9kZWxzL3Byb2dyZXNzX21vZGVscy5kYXJ0Jzs=",
  ),
  _Patch(
    path: "lib/core/state/game_controller.dart",
    label: "GameController learnerStage getters",
    oldBase64: "ICBpbnQgZ2V0IHN0cmVhayA9PiBfcHJvZmlsZS5zdHJlYWs7CiAgaW50IGdldCBzZWxlY3RlZENsYXNzID0+IF9wcm9maWxlLnNlbGVjdGVkQ2xhc3M7CiAgaW50IGdldCB4cCA9PiBfcHJvZmlsZS54cDs=",
    newBase64: "ICBpbnQgZ2V0IHN0cmVhayA9PiBfcHJvZmlsZS5zdHJlYWs7CiAgaW50IGdldCBzZWxlY3RlZENsYXNzID0+IF9wcm9maWxlLnNlbGVjdGVkQ2xhc3M7CiAgTGVhcm5lclN0YWdlIGdldCBsZWFybmVyU3RhZ2UgPT4gX3Byb2ZpbGUubGVhcm5lclN0YWdlOwogIGJvb2wgZ2V0IGlzTnVyc2VyeUxlYXJuZXIgPT4gbGVhcm5lclN0YWdlID09IExlYXJuZXJTdGFnZS5udXJzZXJ5OwogIGludCBnZXQgeHAgPT4gX3Byb2ZpbGUueHA7",
  ),
  _Patch(
    path: "lib/core/state/game_controller.dart",
    label: "GameController setLearnerStage",
    oldBase64: "ICB2b2lkIHNldENsYXNzKGludCB2YWx1ZSkgewogICAgaWYgKHZhbHVlIDwgMyB8fCB2YWx1ZSA+IDUgfHwgdmFsdWUgPT0gX3Byb2ZpbGUuc2VsZWN0ZWRDbGFzcykgcmV0dXJuOwogICAgX2ZvcmVncm91bmRTZXNzaW9uS2V5cy5yZW1vdmUoYWN0aXZlUHJvZmlsZUlkKTsKICAgIF9wcm9maWxlLnNlbGVjdGVkQ2xhc3MgPSB2YWx1ZTsKICAgIF9jaGFuZ2VkKCk7CiAgfQoKICB2b2lkIHNldFNvdW5kRW5hYmxlZChib29sIHZhbHVlKSB7",
    newBase64: "ICB2b2lkIHNldENsYXNzKGludCB2YWx1ZSkgewogICAgaWYgKHZhbHVlIDwgMyB8fCB2YWx1ZSA+IDUgfHwgdmFsdWUgPT0gX3Byb2ZpbGUuc2VsZWN0ZWRDbGFzcykgcmV0dXJuOwogICAgX2ZvcmVncm91bmRTZXNzaW9uS2V5cy5yZW1vdmUoYWN0aXZlUHJvZmlsZUlkKTsKICAgIF9wcm9maWxlLnNlbGVjdGVkQ2xhc3MgPSB2YWx1ZTsKICAgIF9jaGFuZ2VkKCk7CiAgfQoKICB2b2lkIHNldExlYXJuZXJTdGFnZShMZWFybmVyU3RhZ2UgdmFsdWUpIHsKICAgIGlmIChfcHJvZmlsZS5sZWFybmVyU3RhZ2UgPT0gdmFsdWUpIHJldHVybjsKICAgIF9mb3JlZ3JvdW5kU2Vzc2lvbktleXMucmVtb3ZlKGFjdGl2ZVByb2ZpbGVJZCk7CiAgICBfcHJvZmlsZS5sZWFybmVyU3RhZ2UgPSB2YWx1ZTsKICAgIGlmICh2YWx1ZSA9PSBMZWFybmVyU3RhZ2UubnVyc2VyeSkgewogICAgICBfcHJvZmlsZS5udXJzZXJ5TGVhcm5pbmcgPSBfbnVyc2VyeVByb2dyZXNzLnJlZnJlc2hSZXZpZXdTdGF0ZXMoCiAgICAgICAgX3Byb2ZpbGUubnVyc2VyeUxlYXJuaW5nLAogICAgICAgIERhdGVUaW1lLm5vdygpLAogICAgICApOwogICAgfQogICAgX2NoYW5nZWQoKTsKICB9CgogIHZvaWQgc2V0U291bmRFbmFibGVkKGJvb2wgdmFsdWUpIHs=",
  ),
  _Patch(
    path: "lib/core/state/game_controller.dart",
    label: "createProfile learnerStage parameter",
    oldBase64: "ICBTdHJpbmcgY3JlYXRlUHJvZmlsZSh7CiAgICByZXF1aXJlZCBTdHJpbmcgbmFtZSwKICAgIHJlcXVpcmVkIGludCBjbGFzc051bWJlciwKICAgIFN0cmluZyBhdmF0YXJFbW9qaSA9ICfwn6eSJywKICB9KSB7",
    newBase64: "ICBTdHJpbmcgY3JlYXRlUHJvZmlsZSh7CiAgICByZXF1aXJlZCBTdHJpbmcgbmFtZSwKICAgIHJlcXVpcmVkIGludCBjbGFzc051bWJlciwKICAgIExlYXJuZXJTdGFnZSBsZWFybmVyU3RhZ2UgPSBMZWFybmVyU3RhZ2Uuc2Nob29sLAogICAgU3RyaW5nIGF2YXRhckVtb2ppID0gJ/Cfp5InLAogIH0pIHs=",
  ),
  _Patch(
    path: "lib/core/state/game_controller.dart",
    label: "createProfile learnerStage persistence",
    oldBase64: "ICAgICAgbmFtZTogdHJpbW1lZC5sZW5ndGggPiAyNCA/IHRyaW1tZWQuc3Vic3RyaW5nKDAsIDI0KSA6IHRyaW1tZWQsCiAgICAgIGF2YXRhckVtb2ppOiBhdmF0YXJFbW9qaSwKICAgICAgc2VsZWN0ZWRDbGFzczogbm9ybWFsaXplZENsYXNzLA==",
    newBase64: "ICAgICAgbmFtZTogdHJpbW1lZC5sZW5ndGggPiAyNCA/IHRyaW1tZWQuc3Vic3RyaW5nKDAsIDI0KSA6IHRyaW1tZWQsCiAgICAgIGF2YXRhckVtb2ppOiBhdmF0YXJFbW9qaSwKICAgICAgbGVhcm5lclN0YWdlOiBsZWFybmVyU3RhZ2UsCiAgICAgIHNlbGVjdGVkQ2xhc3M6IG5vcm1hbGl6ZWRDbGFzcyw=",
  ),
  _Patch(
    path: "lib/core/state/game_controller.dart",
    label: "switchProfile refreshes Nursery review state",
    oldBase64: "ICAgIF9wcm9maWxlLmxlYXJuaW5nID0gX2xlYXJuaW5nUHJvZ3Jlc3MucmVmcmVzaFJldmlld1N0YXRlcygKICAgICAgX3Byb2ZpbGUubGVhcm5pbmcsCiAgICAgIERhdGVUaW1lLm5vdygpLAogICAgKTsKICAgIF9jaGFuZ2VkKCk7CiAgICByZXR1cm4gdHJ1ZTs=",
    newBase64: "ICAgIF9wcm9maWxlLmxlYXJuaW5nID0gX2xlYXJuaW5nUHJvZ3Jlc3MucmVmcmVzaFJldmlld1N0YXRlcygKICAgICAgX3Byb2ZpbGUubGVhcm5pbmcsCiAgICAgIERhdGVUaW1lLm5vdygpLAogICAgKTsKICAgIF9wcm9maWxlLm51cnNlcnlMZWFybmluZyA9IF9udXJzZXJ5UHJvZ3Jlc3MucmVmcmVzaFJldmlld1N0YXRlcygKICAgICAgX3Byb2ZpbGUubnVyc2VyeUxlYXJuaW5nLAogICAgICBEYXRlVGltZS5ub3coKSwKICAgICk7CiAgICBfY2hhbmdlZCgpOwogICAgcmV0dXJuIHRydWU7",
  ),
  _Patch(
    path: "lib/core/state/game_controller.dart",
    label: "resetProgress preserves learnerStage",
    oldBase64: "ICAgICAgbmFtZTogY3VycmVudC5uYW1lLAogICAgICBhdmF0YXJFbW9qaTogY3VycmVudC5hdmF0YXJFbW9qaSwKICAgICAgc2VsZWN0ZWRDbGFzczogY3VycmVudC5zZWxlY3RlZENsYXNzLA==",
    newBase64: "ICAgICAgbmFtZTogY3VycmVudC5uYW1lLAogICAgICBhdmF0YXJFbW9qaTogY3VycmVudC5hdmF0YXJFbW9qaSwKICAgICAgbGVhcm5lclN0YWdlOiBjdXJyZW50LmxlYXJuZXJTdGFnZSwKICAgICAgc2VsZWN0ZWRDbGFzczogY3VycmVudC5zZWxlY3RlZENsYXNzLA==",
  ),
  _Patch(
    path: "lib/features/nursery/nursery_home_screen.dart",
    label: "NurseryHomeScreen root-mode contract",
    oldBase64: "Y2xhc3MgTnVyc2VyeUhvbWVTY3JlZW4gZXh0ZW5kcyBTdGF0ZWxlc3NXaWRnZXQgewogIGNvbnN0IE51cnNlcnlIb21lU2NyZWVuKHtzdXBlci5rZXl9KTsKCiAgQG92ZXJyaWRl",
    newBase64: "Y2xhc3MgTnVyc2VyeUhvbWVTY3JlZW4gZXh0ZW5kcyBTdGF0ZWxlc3NXaWRnZXQgewogIGNvbnN0IE51cnNlcnlIb21lU2NyZWVuKHsKICAgIHRoaXMucm9vdE1vZGUgPSBmYWxzZSwKICAgIHRoaXMub25PcGVuR3Jvd25VcEFyZWEsCiAgICBzdXBlci5rZXksCiAgfSk7CgogIGZpbmFsIGJvb2wgcm9vdE1vZGU7CiAgZmluYWwgVm9pZENhbGxiYWNrPyBvbk9wZW5Hcm93blVwQXJlYTsKCiAgQG92ZXJyaWRl",
  ),
  _Patch(
    path: "lib/features/nursery/nursery_home_screen.dart",
    label: "Nursery root header and grown-up boundary",
    oldBase64: "ICAgICAgICAgICAgQnJpZ2h0SGVhZGVyKAogICAgICAgICAgICAgIHNob3dCYWNrOiB0cnVlLAogICAgICAgICAgICAgIHRpdGxlOiAnTnVyc2VyeSBMZWFybmluZyBHYXJkZW4nLAogICAgICAgICAgICAgIHRyYWlsaW5nOiBJY29uQnV0dG9uKAogICAgICAgICAgICAgICAgdG9vbHRpcDogJ0hlYXIgd2VsY29tZScsCiAgICAgICAgICAgICAgICBvblByZXNzZWQ6ICgpID0+IHVuYXdhaXRlZCgKICAgICAgICAgICAgICAgICAgQnJpZ2h0QXVkaW9TZXJ2aWNlLmluc3RhbmNlLnNwZWFrKAogICAgICAgICAgICAgICAgICAgICdXZWxjb21lIHRvIE51cnNlcnkgUGxheS4gVGFwIHRoZSBiaWcgcGxheSBidXR0b24sIG9yIGNob29zZSBhIHdvcmxkLicsCiAgICAgICAgICAgICAgICAgICAgbWFudWFsOiB0cnVlLAogICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgIGljb246IGNvbnN0IEljb24oSWNvbnMudm9sdW1lX3VwX3JvdW5kZWQpLAogICAgICAgICAgICAgICksCiAgICAgICAgICAgICks",
    newBase64: "ICAgICAgICAgICAgQnJpZ2h0SGVhZGVyKAogICAgICAgICAgICAgIHNob3dCYWNrOiAhcm9vdE1vZGUsCiAgICAgICAgICAgICAgdGl0bGU6ICdOdXJzZXJ5IExlYXJuaW5nIEdhcmRlbicsCiAgICAgICAgICAgICAgdHJhaWxpbmc6IFJvdygKICAgICAgICAgICAgICAgIG1haW5BeGlzU2l6ZTogTWFpbkF4aXNTaXplLm1pbiwKICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICAgICAgICAgIEljb25CdXR0b24oCiAgICAgICAgICAgICAgICAgICAgdG9vbHRpcDogJ0hlYXIgd2VsY29tZScsCiAgICAgICAgICAgICAgICAgICAgb25QcmVzc2VkOiAoKSA9PiB1bmF3YWl0ZWQoCiAgICAgICAgICAgICAgICAgICAgICBCcmlnaHRBdWRpb1NlcnZpY2UuaW5zdGFuY2Uuc3BlYWsoCiAgICAgICAgICAgICAgICAgICAgICAgICdXZWxjb21lIHRvIE51cnNlcnkgUGxheS4gVGFwIHRoZSBiaWcgcGxheSBidXR0b24sIG9yIGNob29zZSBhIHdvcmxkLicsCiAgICAgICAgICAgICAgICAgICAgICAgIG1hbnVhbDogdHJ1ZSwKICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICBpY29uOiBjb25zdCBJY29uKEljb25zLnZvbHVtZV91cF9yb3VuZGVkKSwKICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgaWYgKHJvb3RNb2RlICYmIG9uT3Blbkdyb3duVXBBcmVhICE9IG51bGwpCiAgICAgICAgICAgICAgICAgICAgSWNvbkJ1dHRvbigKICAgICAgICAgICAgICAgICAgICAgIGtleTogY29uc3QgS2V5KCdudXJzZXJ5X2dyb3duX3VwX2FyZWEnKSwKICAgICAgICAgICAgICAgICAgICAgIHRvb2x0aXA6ICdHcm93bi11cCBhcmVhJywKICAgICAgICAgICAgICAgICAgICAgIG9uUHJlc3NlZDogb25PcGVuR3Jvd25VcEFyZWEsCiAgICAgICAgICAgICAgICAgICAgICBpY29uOiBjb25zdCBJY29uKEljb25zLnN1cGVydmlzb3JfYWNjb3VudF9yb3VuZGVkKSwKICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICApLAogICAgICAgICAgICApLA==",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Parent Dashboard LearnerStage import",
    oldBase64: "aW1wb3J0ICcuLi8uLi9jb3JlL21vZGVscy9nYW1lX21vZGVscy5kYXJ0JzsKaW1wb3J0ICcuLi8uLi9jb3JlL21vZGVscy9wcm9ncmVzc19tb2RlbHMuZGFydCc7",
    newBase64: "aW1wb3J0ICcuLi8uLi9jb3JlL21vZGVscy9nYW1lX21vZGVscy5kYXJ0JzsKaW1wb3J0ICcuLi8uLi9jb3JlL21vZGVscy9sZWFybmVyX3N0YWdlLmRhcnQnOwppbXBvcnQgJy4uLy4uL2NvcmUvbW9kZWxzL3Byb2dyZXNzX21vZGVscy5kYXJ0Jzs=",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Parent active learner stage label",
    oldBase64: "ICAgICAgICAgICAgICAgICcke2NvbnRyb2xsZXIuYWN0aXZlUHJvZmlsZUF2YXRhcn0gJHtjb250cm9sbGVyLmFjdGl2ZVByb2ZpbGVOYW1lfSDigKIgQ2xhc3MgJHtjb250cm9sbGVyLnNlbGVjdGVkQ2xhc3N9Jyw=",
    newBase64: "ICAgICAgICAgICAgICAgICcke2NvbnRyb2xsZXIuYWN0aXZlUHJvZmlsZUF2YXRhcn0gJHtjb250cm9sbGVyLmFjdGl2ZVByb2ZpbGVOYW1lfSDigKIgJHtjb250cm9sbGVyLmlzTnVyc2VyeUxlYXJuZXIgPyAnTnVyc2VyeScgOiAnQ2xhc3MgJHtjb250cm9sbGVyLnNlbGVjdGVkQ2xhc3N9J30nLA==",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Parent stage selector",
    oldBase64: "ICAgICAgICAgICAgICAgICAgICAgIERyb3Bkb3duQnV0dG9uRm9ybUZpZWxkPGludD4oCiAgICAgICAgICAgICAgICAgICAgICAgIGtleTogVmFsdWVLZXk8U3RyaW5nPigKICAgICAgICAgICAgICAgICAgICAgICAgICAgICdjbGFzcy0ke2NvbnRyb2xsZXIuYWN0aXZlUHJvZmlsZUlkfScpLAogICAgICAgICAgICAgICAgICAgICAgICBpbml0aWFsVmFsdWU6IGNvbnRyb2xsZXIuc2VsZWN0ZWRDbGFzcywKICAgICAgICAgICAgICAgICAgICAgICAgZGVjb3JhdGlvbjoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNvbnN0IElucHV0RGVjb3JhdGlvbihsYWJlbFRleHQ6ICdTY2hvb2wgY2xhc3MnKSwKICAgICAgICAgICAgICAgICAgICAgICAgaXRlbXM6IGNvbnN0IFszLCA0LCA1XQogICAgICAgICAgICAgICAgICAgICAgICAgICAgLm1hcCgodmFsdWUpID0+IERyb3Bkb3duTWVudUl0ZW08aW50PigKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB2YWx1ZTogdmFsdWUsIGNoaWxkOiBUZXh0KCdDbGFzcyAkdmFsdWUnKSkpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAudG9MaXN0KCksCiAgICAgICAgICAgICAgICAgICAgICAgIG9uQ2hhbmdlZDogKHZhbHVlKSB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgKHZhbHVlICE9IG51bGwpIGNvbnRyb2xsZXIuc2V0Q2xhc3ModmFsdWUpOwogICAgICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgICAgKSw=",
    newBase64: "ICAgICAgICAgICAgICAgICAgICAgIERyb3Bkb3duQnV0dG9uRm9ybUZpZWxkPExlYXJuZXJTdGFnZT4oCiAgICAgICAgICAgICAgICAgICAgICAgIGtleTogVmFsdWVLZXk8U3RyaW5nPigKICAgICAgICAgICAgICAgICAgICAgICAgICAgICdzdGFnZS0ke2NvbnRyb2xsZXIuYWN0aXZlUHJvZmlsZUlkfScpLAogICAgICAgICAgICAgICAgICAgICAgICBpbml0aWFsVmFsdWU6IGNvbnRyb2xsZXIubGVhcm5lclN0YWdlLAogICAgICAgICAgICAgICAgICAgICAgICBkZWNvcmF0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgY29uc3QgSW5wdXREZWNvcmF0aW9uKGxhYmVsVGV4dDogJ0xlYXJuaW5nIHN0YWdlJyksCiAgICAgICAgICAgICAgICAgICAgICAgIGl0ZW1zOiBjb25zdCBbCiAgICAgICAgICAgICAgICAgICAgICAgICAgRHJvcGRvd25NZW51SXRlbTxMZWFybmVyU3RhZ2U+KAogICAgICAgICAgICAgICAgICAgICAgICAgICAgdmFsdWU6IExlYXJuZXJTdGFnZS5udXJzZXJ5LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgY2hpbGQ6IFRleHQoJ051cnNlcnknKSwKICAgICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICAgIERyb3Bkb3duTWVudUl0ZW08TGVhcm5lclN0YWdlPigKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOiBMZWFybmVyU3RhZ2Uuc2Nob29sLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgY2hpbGQ6IFRleHQoJ1NjaG9vbCcpLAogICAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAgICAgICAgIG9uQ2hhbmdlZDogKHZhbHVlKSB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgKHZhbHVlICE9IG51bGwpIHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNvbnRyb2xsZXIuc2V0TGVhcm5lclN0YWdlKHZhbHVlKTsKICAgICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgaWYgKCFjb250cm9sbGVyLmlzTnVyc2VyeUxlYXJuZXIpIC4uLlsKICAgICAgICAgICAgICAgICAgICAgICAgY29uc3QgU2l6ZWRCb3goaGVpZ2h0OiAxMCksCiAgICAgICAgICAgICAgICAgICAgICAgIERyb3Bkb3duQnV0dG9uRm9ybUZpZWxkPGludD4oCiAgICAgICAgICAgICAgICAgICAgICAgICAga2V5OiBWYWx1ZUtleTxTdHJpbmc+KAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnY2xhc3MtJHtjb250cm9sbGVyLmFjdGl2ZVByb2ZpbGVJZH0nKSwKICAgICAgICAgICAgICAgICAgICAgICAgICBpbml0aWFsVmFsdWU6IGNvbnRyb2xsZXIuc2VsZWN0ZWRDbGFzcywKICAgICAgICAgICAgICAgICAgICAgICAgICBkZWNvcmF0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb25zdCBJbnB1dERlY29yYXRpb24obGFiZWxUZXh0OiAnU2Nob29sIGNsYXNzJyksCiAgICAgICAgICAgICAgICAgICAgICAgICAgaXRlbXM6IGNvbnN0IFszLCA0LCA1XQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAubWFwKCh2YWx1ZSkgPT4gRHJvcGRvd25NZW51SXRlbTxpbnQ+KAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdmFsdWU6IHZhbHVlLCBjaGlsZDogVGV4dCgnQ2xhc3MgJHZhbHVlJykpKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAudG9MaXN0KCksCiAgICAgICAgICAgICAgICAgICAgICAgICAgb25DaGFuZ2VkOiAodmFsdWUpIHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmICh2YWx1ZSAhPSBudWxsKSBjb250cm9sbGVyLnNldENsYXNzKHZhbHVlKTsKICAgICAgICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgXSw=",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Profile chip stage label",
    oldBase64: "ICAgICAgICAgICAgICAgICAgbGFiZWw6IFRleHQoJyR7cHJvZmlsZS5uYW1lfSDigKIgQyR7cHJvZmlsZS5zZWxlY3RlZENsYXNzfScpLA==",
    newBase64: "ICAgICAgICAgICAgICAgICAgbGFiZWw6IFRleHQoCiAgICAgICAgICAgICAgICAgICAgcHJvZmlsZS5sZWFybmVyU3RhZ2UgPT0gTGVhcm5lclN0YWdlLm51cnNlcnkKICAgICAgICAgICAgICAgICAgICAgICAgPyAnJHtwcm9maWxlLm5hbWV9IOKAoiBOdXJzZXJ5JwogICAgICAgICAgICAgICAgICAgICAgICA6ICcke3Byb2ZpbGUubmFtZX0g4oCiIEMke3Byb2ZpbGUuc2VsZWN0ZWRDbGFzc30nLAogICAgICAgICAgICAgICAgICApLA==",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Add-profile learnerStage state",
    oldBase64: "ICAgIGZpbmFsIG5hbWVDb250cm9sbGVyID0gVGV4dEVkaXRpbmdDb250cm9sbGVyKCk7CiAgICB2YXIgY2xhc3NOdW1iZXIgPSAzOwogICAgdmFyIGF2YXRhciA9ICfwn6eSJzs=",
    newBase64: "ICAgIGZpbmFsIG5hbWVDb250cm9sbGVyID0gVGV4dEVkaXRpbmdDb250cm9sbGVyKCk7CiAgICB2YXIgbGVhcm5lclN0YWdlID0gTGVhcm5lclN0YWdlLnNjaG9vbDsKICAgIHZhciBjbGFzc051bWJlciA9IDM7CiAgICB2YXIgYXZhdGFyID0gJ/Cfp5InOw==",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Add-profile stage and school-class selector",
    oldBase64: "ICAgICAgICAgICAgICAgIERyb3Bkb3duQnV0dG9uRm9ybUZpZWxkPGludD4oCiAgICAgICAgICAgICAgICAgIGluaXRpYWxWYWx1ZTogY2xhc3NOdW1iZXIsCiAgICAgICAgICAgICAgICAgIGRlY29yYXRpb246IGNvbnN0IElucHV0RGVjb3JhdGlvbihsYWJlbFRleHQ6ICdDbGFzcycpLAogICAgICAgICAgICAgICAgICBpdGVtczogY29uc3QgWzMsIDQsIDVdCiAgICAgICAgICAgICAgICAgICAgICAubWFwKCh2YWx1ZSkgPT4gRHJvcGRvd25NZW51SXRlbSgKICAgICAgICAgICAgICAgICAgICAgICAgICB2YWx1ZTogdmFsdWUsIGNoaWxkOiBUZXh0KCdDbGFzcyAkdmFsdWUnKSkpCiAgICAgICAgICAgICAgICAgICAgICAudG9MaXN0KCksCiAgICAgICAgICAgICAgICAgIG9uQ2hhbmdlZDogKHZhbHVlKSB7CiAgICAgICAgICAgICAgICAgICAgaWYgKHZhbHVlICE9IG51bGwpCiAgICAgICAgICAgICAgICAgICAgICBzZXREaWFsb2dTdGF0ZSgoKSA9PiBjbGFzc051bWJlciA9IHZhbHVlKTsKICAgICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICks",
    newBase64: "ICAgICAgICAgICAgICAgIERyb3Bkb3duQnV0dG9uRm9ybUZpZWxkPExlYXJuZXJTdGFnZT4oCiAgICAgICAgICAgICAgICAgIGluaXRpYWxWYWx1ZTogbGVhcm5lclN0YWdlLAogICAgICAgICAgICAgICAgICBkZWNvcmF0aW9uOgogICAgICAgICAgICAgICAgICAgICAgY29uc3QgSW5wdXREZWNvcmF0aW9uKGxhYmVsVGV4dDogJ0xlYXJuaW5nIHN0YWdlJyksCiAgICAgICAgICAgICAgICAgIGl0ZW1zOiBjb25zdCBbCiAgICAgICAgICAgICAgICAgICAgRHJvcGRvd25NZW51SXRlbTxMZWFybmVyU3RhZ2U+KAogICAgICAgICAgICAgICAgICAgICAgdmFsdWU6IExlYXJuZXJTdGFnZS5udXJzZXJ5LAogICAgICAgICAgICAgICAgICAgICAgY2hpbGQ6IFRleHQoJ051cnNlcnknKSwKICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgIERyb3Bkb3duTWVudUl0ZW08TGVhcm5lclN0YWdlPigKICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOiBMZWFybmVyU3RhZ2Uuc2Nob29sLAogICAgICAgICAgICAgICAgICAgICAgY2hpbGQ6IFRleHQoJ1NjaG9vbCcpLAogICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAgIG9uQ2hhbmdlZDogKHZhbHVlKSB7CiAgICAgICAgICAgICAgICAgICAgaWYgKHZhbHVlICE9IG51bGwpIHsKICAgICAgICAgICAgICAgICAgICAgIHNldERpYWxvZ1N0YXRlKCgpID0+IGxlYXJuZXJTdGFnZSA9IHZhbHVlKTsKICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgaWYgKGxlYXJuZXJTdGFnZSA9PSBMZWFybmVyU3RhZ2Uuc2Nob29sKSAuLi5bCiAgICAgICAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTApLAogICAgICAgICAgICAgICAgICBEcm9wZG93bkJ1dHRvbkZvcm1GaWVsZDxpbnQ+KAogICAgICAgICAgICAgICAgICAgIGluaXRpYWxWYWx1ZTogY2xhc3NOdW1iZXIsCiAgICAgICAgICAgICAgICAgICAgZGVjb3JhdGlvbjogY29uc3QgSW5wdXREZWNvcmF0aW9uKGxhYmVsVGV4dDogJ0NsYXNzJyksCiAgICAgICAgICAgICAgICAgICAgaXRlbXM6IGNvbnN0IFszLCA0LCA1XQogICAgICAgICAgICAgICAgICAgICAgICAubWFwKCh2YWx1ZSkgPT4gRHJvcGRvd25NZW51SXRlbSgKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOiB2YWx1ZSwgY2hpbGQ6IFRleHQoJ0NsYXNzICR2YWx1ZScpKSkKICAgICAgICAgICAgICAgICAgICAgICAgLnRvTGlzdCgpLAogICAgICAgICAgICAgICAgICAgIG9uQ2hhbmdlZDogKHZhbHVlKSB7CiAgICAgICAgICAgICAgICAgICAgICBpZiAodmFsdWUgIT0gbnVsbCkgewogICAgICAgICAgICAgICAgICAgICAgICBzZXREaWFsb2dTdGF0ZSgoKSA9PiBjbGFzc051bWJlciA9IHZhbHVlKTsKICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgXSw=",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Add-profile learnerStage creation",
    oldBase64: "ICAgICAgZmluYWwgaWQgPSBjb250cm9sbGVyLmNyZWF0ZVByb2ZpbGUoCiAgICAgICAgICBuYW1lOiBuYW1lQ29udHJvbGxlci50ZXh0LAogICAgICAgICAgY2xhc3NOdW1iZXI6IGNsYXNzTnVtYmVyLAogICAgICAgICAgYXZhdGFyRW1vamk6IGF2YXRhcik7",
    newBase64: "ICAgICAgZmluYWwgaWQgPSBjb250cm9sbGVyLmNyZWF0ZVByb2ZpbGUoCiAgICAgICAgbmFtZTogbmFtZUNvbnRyb2xsZXIudGV4dCwKICAgICAgICBjbGFzc051bWJlcjogY2xhc3NOdW1iZXIsCiAgICAgICAgbGVhcm5lclN0YWdlOiBsZWFybmVyU3RhZ2UsCiAgICAgICAgYXZhdGFyRW1vamk6IGF2YXRhciwKICAgICAgKTs=",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Nursery parent summary",
    oldBase64: "ICAgICAgICAgICAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTApLAogICAgICAgICAgICAgICAgICAgICAgX1JvdygKICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ0xldmVsIC8gWFAnLAogICAgICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnTHYgJHtjb250cm9sbGVyLmxldmVsfSDigKIgJHtjb250cm9sbGVyLnhwfSBYUCcpLAogICAgICAgICAgICAgICAgICAgICAgX1JvdyhsYWJlbDogJ0FsbC10aW1lIGFjY3VyYWN5JywgdmFsdWU6ICckYWNjdXJhY3klJyksCiAgICAgICAgICAgICAgICAgICAgICBfUm93KAogICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ1RvZGF5JywKICAgICAgICAgICAgICAgICAgICAgICAgdmFsdWU6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAnJHtjb250cm9sbGVyLmNvcnJlY3RUb2RheX0vJHtjb250cm9sbGVyLmFuc3dlcnNUb2RheX0gY29ycmVjdCAoJGRhaWx5QWNjdXJhY3klKScsCiAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgX1JvdygKICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ0xlYXJuaW5nIHN0cmVhaycsCiAgICAgICAgICAgICAgICAgICAgICAgICAgdmFsdWU6ICcke2NvbnRyb2xsZXIuc3RyZWFrfSBkYXlzJyksCiAgICAgICAgICAgICAgICAgICAgICBfUm93KAogICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ1N0dWR5IHRpbWUgdG9kYXknLAogICAgICAgICAgICAgICAgICAgICAgICB2YWx1ZTogJyR7Y29udHJvbGxlci5zdHVkeU1pbnV0ZXNUb2RheS5mbG9vcigpfSBtaW4nLAogICAgICAgICAgICAgICAgICAgICAgKSw=",
    newBase64: "ICAgICAgICAgICAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTApLAogICAgICAgICAgICAgICAgICAgICAgaWYgKGNvbnRyb2xsZXIuaXNOdXJzZXJ5TGVhcm5lcikgLi4uWwogICAgICAgICAgICAgICAgICAgICAgICBfUm93KAogICAgICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnTnVyc2VyeSBhY3Rpdml0aWVzIHJlY29yZGVkJywKICAgICAgICAgICAgICAgICAgICAgICAgICB2YWx1ZTogJyR7Y29udHJvbGxlci5udXJzZXJ5QXR0ZW1wdEV2aWRlbmNlLmxlbmd0aH0nLAogICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICBfUm93KAogICAgICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnUmV2aWV3IHJlYWR5JywKICAgICAgICAgICAgICAgICAgICAgICAgICB2YWx1ZToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJyR7Y29udHJvbGxlci5kdWVOdXJzZXJ5UmV2aWV3VGFza3MobGltaXQ6IDUwKS5sZW5ndGh9JywKICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgIF0gZWxzZSAuLi5bCiAgICAgICAgICAgICAgICAgICAgICAgIF9Sb3coCiAgICAgICAgICAgICAgICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCAvIFhQJywKICAgICAgICAgICAgICAgICAgICAgICAgICB2YWx1ZToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ0x2ICR7Y29udHJvbGxlci5sZXZlbH0g4oCiICR7Y29udHJvbGxlci54cH0gWFAnLAogICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICBfUm93KAogICAgICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnQWxsLXRpbWUgYWNjdXJhY3knLAogICAgICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOiAnJGFjY3VyYWN5JScsCiAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICAgIF9Sb3coCiAgICAgICAgICAgICAgICAgICAgICAgICAgbGFiZWw6ICdUb2RheScsCiAgICAgICAgICAgICAgICAgICAgICAgICAgdmFsdWU6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICcke2NvbnRyb2xsZXIuY29ycmVjdFRvZGF5fS8ke2NvbnRyb2xsZXIuYW5zd2Vyc1RvZGF5fSBjb3JyZWN0ICgkZGFpbHlBY2N1cmFjeSUpJywKICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgX1JvdygKICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ0xlYXJuaW5nIHN0cmVhaycsCiAgICAgICAgICAgICAgICAgICAgICAgICAgdmFsdWU6ICcke2NvbnRyb2xsZXIuc3RyZWFrfSBkYXlzJywKICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgX1JvdygKICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ1N0dWR5IHRpbWUgdG9kYXknLAogICAgICAgICAgICAgICAgICAgICAgICAgIHZhbHVlOiAnJHtjb250cm9sbGVyLnN0dWR5TWludXRlc1RvZGF5LmZsb29yKCl9IG1pbicsCiAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICBdLA==",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Hide School analytics start for Nursery",
    oldBase64: "ICAgICAgICAgICAgICBjb25zdCBTaXplZEJveChoZWlnaHQ6IDE4KSwKICAgICAgICAgICAgICBjb25zdCBUZXh0KAogICAgICAgICAgICAgICAgJ0NsYXNzIGFkdmVudHVyZSBtYXAnLA==",
    newBase64: "ICAgICAgICAgICAgICBpZiAoIWNvbnRyb2xsZXIuaXNOdXJzZXJ5TGVhcm5lcikgLi4uWwogICAgICAgICAgICAgICAgY29uc3QgU2l6ZWRCb3goaGVpZ2h0OiAxOCksCiAgICAgICAgICAgICAgICBjb25zdCBUZXh0KAogICAgICAgICAgICAgICAgICAnQ2xhc3MgYWR2ZW50dXJlIG1hcCcs",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Hide School analytics end for Nursery",
    oldBase64: "ICAgICAgICAgICAgICBjb25zdCBTaXplZEJveChoZWlnaHQ6IDE4KSwKICAgICAgICAgICAgICBjb25zdCBUZXh0KAogICAgICAgICAgICAgICAgJ1JlYWRpbmcgJiBhY2Nlc3NpYmlsaXR5Jyw=",
    newBase64: "ICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTgpLAogICAgICAgICAgICAgIGNvbnN0IFRleHQoCiAgICAgICAgICAgICAgICAnUmVhZGluZyAmIGFjY2Vzc2liaWxpdHknLA==",
  ),
  _Patch(
    path: "lib/features/parent/parent_dashboard_screen.dart",
    label: "Hide School daily challenges for Nursery",
    oldBase64: "ICAgICAgICAgICAgICBjb25zdCBTaXplZEJveChoZWlnaHQ6IDE4KSwKICAgICAgICAgICAgICBfRGFpbHlDaGFsbGVuZ2VPdmVydmlldyhjb250cm9sbGVyOiBjb250cm9sbGVyKSw=",
    newBase64: "ICAgICAgICAgICAgICBpZiAoIWNvbnRyb2xsZXIuaXNOdXJzZXJ5TGVhcm5lcikgLi4uWwogICAgICAgICAgICAgICAgY29uc3QgU2l6ZWRCb3goaGVpZ2h0OiAxOCksCiAgICAgICAgICAgICAgICBfRGFpbHlDaGFsbGVuZ2VPdmVydmlldyhjb250cm9sbGVyOiBjb250cm9sbGVyKSwKICAgICAgICAgICAgICBdLA==",
  ),
  _Patch(
    path: "lib/widgets/bright_widgets.dart",
    label: "Mission summary LearningSessionExit import",
    oldBase64: "aW1wb3J0ICcuLi9jb3JlL21vZGVscy9wcm9ncmVzc19tb2RlbHMuZGFydCc7CmltcG9ydCAnLi4vY29yZS9wcmVzZW50YXRpb24vZ2FtZV9mZWVsX2RpcmVjdG9yLmRhcnQnOw==",
    newBase64: "aW1wb3J0ICcuLi9jb3JlL21vZGVscy9wcm9ncmVzc19tb2RlbHMuZGFydCc7CmltcG9ydCAnLi4vY29yZS9wcmVzZW50YXRpb24vZ2FtZV9mZWVsX2RpcmVjdG9yLmRhcnQnOwppbXBvcnQgJy4uL2NvcmUvc2Vzc2lvbi9sZWFybmluZ19zZXNzaW9uX2V4aXQuZGFydCc7",
  ),
  _Patch(
    path: "lib/widgets/bright_widgets.dart",
    label: "Header learner-stage label and false affordance removal",
    oldBase64: "ICAgICAgICAgICAgICAgICAgdGl0bGUgPT0gbnVsbAogICAgICAgICAgICAgICAgICAgICAgPyAnQ2xhc3MgJHtjb250cm9sbGVyLnNlbGVjdGVkQ2xhc3N9ICDilr4nCiAgICAgICAgICAgICAgICAgICAgICA6ICdMZWFybiDigKIgUGxheSDigKIgR3Jvdycs",
    newBase64: "ICAgICAgICAgICAgICAgICAgdGl0bGUgPT0gbnVsbAogICAgICAgICAgICAgICAgICAgICAgPyBjb250cm9sbGVyLmlzTnVyc2VyeUxlYXJuZXIKICAgICAgICAgICAgICAgICAgICAgICAgICA/ICdOdXJzZXJ5JwogICAgICAgICAgICAgICAgICAgICAgICAgIDogJ0NsYXNzICR7Y29udHJvbGxlci5zZWxlY3RlZENsYXNzfScKICAgICAgICAgICAgICAgICAgICAgIDogJ0xlYXJuIOKAoiBQbGF5IOKAoiBHcm93Jyw=",
  ),
  _Patch(
    path: "lib/widgets/bright_widgets.dart",
    label: "Mission result Continue/Replay hierarchy",
    oldBase64: "ICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTYpLAogICAgICAgICAgRmlsbGVkQnV0dG9uLmljb24oCiAgICAgICAgICAgIG9uUHJlc3NlZDogb25SZXBsYXksCiAgICAgICAgICAgIGljb246IGNvbnN0IEljb24oSWNvbnMucmVwbGF5X3JvdW5kZWQpLAogICAgICAgICAgICBsYWJlbDogVGV4dCgKICAgICAgICAgICAgICBjbGVhcmVkCiAgICAgICAgICAgICAgICAgID8gcGxhbi5pc0Jvc3MKICAgICAgICAgICAgICAgICAgICAgID8gJ0NoYWxsZW5nZSBCb3NzIEFnYWluJwogICAgICAgICAgICAgICAgICAgICAgOiAnUmVwbGF5IE1pc3Npb24nCiAgICAgICAgICAgICAgICAgIDogJ1RyeSBBZ2FpbicsCiAgICAgICAgICAgICksCiAgICAgICAgICApLA==",
    newBase64: "ICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTYpLAogICAgICAgICAgaWYgKGNsZWFyZWQpIC4uLlsKICAgICAgICAgICAgRmlsbGVkQnV0dG9uLmljb24oCiAgICAgICAgICAgICAga2V5OiBjb25zdCBLZXkoJ21pc3Npb25fY29udGludWVfYnV0dG9uJyksCiAgICAgICAgICAgICAgb25QcmVzc2VkOiAoKSB7CiAgICAgICAgICAgICAgICBmaW5hbCBuZXh0TGV2ZWxJZCA9IG1vbWVudC5uZXh0TWlzc2lvblBsYW4/LmxldmVsSWQ7CiAgICAgICAgICAgICAgICBOYXZpZ2F0b3Iub2YoY29udGV4dCkucG9wPExlYXJuaW5nU2Vzc2lvbkV4aXQ+KAogICAgICAgICAgICAgICAgICBuZXh0TGV2ZWxJZCA9PSBudWxsCiAgICAgICAgICAgICAgICAgICAgICA/IExlYXJuaW5nU2Vzc2lvbkV4aXQuYmFja1RvV29ybGQKICAgICAgICAgICAgICAgICAgICAgIDogTGVhcm5pbmdTZXNzaW9uRXhpdC5jb250aW51ZVRvTGV2ZWwobmV4dExldmVsSWQpLAogICAgICAgICAgICAgICAgKTsKICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgIGljb246IEljb24oCiAgICAgICAgICAgICAgICBtb21lbnQubmV4dE1pc3Npb25QbGFuID09IG51bGwKICAgICAgICAgICAgICAgICAgICA/IEljb25zLm1hcF9yb3VuZGVkCiAgICAgICAgICAgICAgICAgICAgOiBJY29ucy5hcnJvd19mb3J3YXJkX3JvdW5kZWQsCiAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICBsYWJlbDogVGV4dCgKICAgICAgICAgICAgICAgIG1vbWVudC5uZXh0TWlzc2lvblBsYW4gPT0gbnVsbAogICAgICAgICAgICAgICAgICAgID8gbW9tZW50LndvcmxkQ29tcGxldGUKICAgICAgICAgICAgICAgICAgICAgICAgPyAnQmFjayB0byBXb3JsZHMnCiAgICAgICAgICAgICAgICAgICAgICAgIDogJ0JhY2sgdG8gV29ybGQnCiAgICAgICAgICAgICAgICAgICAgOiAnQ29udGludWUnLAogICAgICAgICAgICAgICksCiAgICAgICAgICAgICksCiAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogOCksCiAgICAgICAgICAgIE91dGxpbmVkQnV0dG9uLmljb24oCiAgICAgICAgICAgICAga2V5OiBjb25zdCBLZXkoJ21pc3Npb25fcmVwbGF5X2J1dHRvbicpLAogICAgICAgICAgICAgIG9uUHJlc3NlZDogb25SZXBsYXksCiAgICAgICAgICAgICAgaWNvbjogY29uc3QgSWNvbihJY29ucy5yZXBsYXlfcm91bmRlZCksCiAgICAgICAgICAgICAgbGFiZWw6IFRleHQoCiAgICAgICAgICAgICAgICBwbGFuLmlzQm9zcyA/ICdDaGFsbGVuZ2UgQm9zcyBBZ2FpbicgOiAnUmVwbGF5IE1pc3Npb24nLAogICAgICAgICAgICAgICksCiAgICAgICAgICAgICksCiAgICAgICAgICBdIGVsc2UKICAgICAgICAgICAgRmlsbGVkQnV0dG9uLmljb24oCiAgICAgICAgICAgICAga2V5OiBjb25zdCBLZXkoJ21pc3Npb25fdHJ5X2FnYWluX2J1dHRvbicpLAogICAgICAgICAgICAgIG9uUHJlc3NlZDogb25SZXBsYXksCiAgICAgICAgICAgICAgaWNvbjogY29uc3QgSWNvbihJY29ucy5yZXBsYXlfcm91bmRlZCksCiAgICAgICAgICAgICAgbGFiZWw6IGNvbnN0IFRleHQoJ1RyeSBBZ2FpbicpLAogICAgICAgICAgICApLA==",
  ),
  _Patch(
    path: "lib/features/games/game_router.dart",
    label: "game_router LearningSessionExit import",
    oldBase64: "aW1wb3J0ICcuLi8uLi9jb3JlL3Nlc3Npb24vZ2FtZV9zZXNzaW9uX21vZGVscy5kYXJ0Jzs=",
    newBase64: "aW1wb3J0ICcuLi8uLi9jb3JlL3Nlc3Npb24vZ2FtZV9zZXNzaW9uX21vZGVscy5kYXJ0JzsKaW1wb3J0ICcuLi8uLi9jb3JlL3Nlc3Npb24vbGVhcm5pbmdfc2Vzc2lvbl9leGl0LmRhcnQnOw==",
  ),
  _Patch(
    path: "lib/features/games/game_router.dart",
    label: "game_router typed result continuation",
    oldBase64: "ICBOYXZpZ2F0b3Iub2YoY29udGV4dCkKICAgICAgLnB1c2goTWF0ZXJpYWxQYWdlUm91dGU8dm9pZD4oYnVpbGRlcjogKF8pID0+IHJvdXRlZFNjcmVlbikpCiAgICAgIC53aGVuQ29tcGxldGUoKCkgewogICAgdW5hd2FpdGVkKGF1ZGlvLnN0b3BWb2ljZSgpKTsKICAgIGZpbmFsIGZpbmlzaGVkU2Vzc2lvbiA9IGNvbnRyb2xsZXIuZ2FtZVNlc3Npb25Gb3IoCiAgICAgIGdhbWVJZDogaWQsCiAgICAgIGNsYXNzTnVtYmVyOiBjbGFzc051bWJlciwKICAgICAgbGVhcm5pbmdMZXZlbElkOiBsZWFybmluZ0xldmVsPy5pZCwKICAgICk7CiAgICBpZiAoZmluaXNoZWRTZXNzaW9uPy5zdGFnZSA9PSBHYW1lU2Vzc2lvblN0YWdlLnJlc3VsdCkgewogICAgICBjb250cm9sbGVyLmRpc2NhcmRHYW1lU2Vzc2lvbihmaW5pc2hlZFNlc3Npb24hKTsKICAgIH0KICAgIGlmIChjb250cm9sbGVyLnNvdW5kRW5hYmxlZCkgewogICAgICB1bmF3YWl0ZWQoYXVkaW8ucGxheU1lbnVNdXNpYyhyZXN0YXJ0OiB0cnVlKSk7CiAgICB9CiAgfSk7",
    newBase64: "ICBOYXZpZ2F0b3Iub2YoY29udGV4dCkKICAgICAgLnB1c2g8TGVhcm5pbmdTZXNzaW9uRXhpdD4oCiAgICAgICAgTWF0ZXJpYWxQYWdlUm91dGU8TGVhcm5pbmdTZXNzaW9uRXhpdD4oYnVpbGRlcjogKF8pID0+IHJvdXRlZFNjcmVlbiksCiAgICAgICkKICAgICAgLnRoZW4oKGV4aXQpIHsKICAgIHVuYXdhaXRlZChhdWRpby5zdG9wVm9pY2UoKSk7CiAgICBmaW5hbCBmaW5pc2hlZFNlc3Npb24gPSBjb250cm9sbGVyLmdhbWVTZXNzaW9uRm9yKAogICAgICBnYW1lSWQ6IGlkLAogICAgICBjbGFzc051bWJlcjogY2xhc3NOdW1iZXIsCiAgICAgIGxlYXJuaW5nTGV2ZWxJZDogbGVhcm5pbmdMZXZlbD8uaWQsCiAgICApOwogICAgaWYgKGZpbmlzaGVkU2Vzc2lvbj8uc3RhZ2UgPT0gR2FtZVNlc3Npb25TdGFnZS5yZXN1bHQpIHsKICAgICAgY29udHJvbGxlci5kaXNjYXJkR2FtZVNlc3Npb24oZmluaXNoZWRTZXNzaW9uISk7CiAgICB9CiAgICBpZiAoY29udHJvbGxlci5zb3VuZEVuYWJsZWQpIHsKICAgICAgdW5hd2FpdGVkKGF1ZGlvLnBsYXlNZW51TXVzaWMocmVzdGFydDogdHJ1ZSkpOwogICAgfQoKICAgIGZpbmFsIG5leHRMZXZlbElkID0gZXhpdD8ubmV4dExldmVsSWQ7CiAgICBmaW5hbCBuZXh0TGV2ZWwgPQogICAgICAgIG5leHRMZXZlbElkID09IG51bGwgPyBudWxsIDogbGVhcm5pbmdMZXZlbEJ5SWQobmV4dExldmVsSWQpOwogICAgaWYgKGV4aXQ/LmFjdGlvbiA9PSBMZWFybmluZ1Nlc3Npb25FeGl0QWN0aW9uLmNvbnRpbnVlTmV4dCAmJgogICAgICAgIG5leHRMZXZlbCAhPSBudWxsICYmCiAgICAgICAgbmV4dExldmVsLmNsYXNzTnVtYmVyID09IGNvbnRyb2xsZXIuc2VsZWN0ZWRDbGFzcyAmJgogICAgICAgIGNvbnRyb2xsZXIuaXNMZXZlbFVubG9ja2VkKG5leHRMZXZlbCkgJiYKICAgICAgICBjb250ZXh0Lm1vdW50ZWQpIHsKICAgICAgV2lkZ2V0c0JpbmRpbmcuaW5zdGFuY2UuYWRkUG9zdEZyYW1lQ2FsbGJhY2soKF8pIHsKICAgICAgICBpZiAoIWNvbnRleHQubW91bnRlZCkgcmV0dXJuOwogICAgICAgIG9wZW5MZWFybmluZ0xldmVsKGNvbnRleHQsIG5leHRMZXZlbCk7CiAgICAgIH0pOwogICAgfQogIH0pOw==",
  ),
];
