/// Bundled Nursery illustration catalog.
///
/// This catalog is generated from the authored A-Z picture associations in
/// `assets/content/nursery/pack_v1.json`. It intentionally contains only
/// assets that already ship with BrightQuest; no network lookup or guessed
/// file path is used by the Nursery visual layer.
abstract final class NurseryAssetCatalog {
  static const Map<String, String> _assetByWord = <String, String>{
    'aeroplane': 'assets/nursery/letter_cards/a_3_aeroplane.png',
    'alligator': 'assets/nursery/letter_cards/a_6_alligator.png',
    'ambulance': 'assets/nursery/letter_cards/a_7_ambulance.png',
    'ant': 'assets/nursery/letter_cards/a_2_ant.png',
    'apple': 'assets/nursery/letter_cards/a_1_apple.png',
    'arrow': 'assets/nursery/letter_cards/a_8_arrow.png',
    'avocado': 'assets/nursery/letter_cards/a_5_avocado.png',
    'axe': 'assets/nursery/letter_cards/a_4_axe.png',
    'ball': 'assets/nursery/letter_cards/b_1_ball.png',
    'balloon': 'assets/nursery/letter_cards/b_8_balloon.png',
    'banana': 'assets/nursery/letter_cards/b_2_banana.png',
    'bird': 'assets/nursery/letter_cards/b_3_bird.png',
    'boat': 'assets/nursery/letter_cards/b_5_boat.png',
    'book': 'assets/nursery/letter_cards/b_6_book.png',
    'box': 'assets/nursery/letter_cards/x_3_box.png',
    'bus': 'assets/nursery/letter_cards/b_4_bus.png',
    'butterfly': 'assets/nursery/letter_cards/b_7_butterfly.png',
    'cake': 'assets/nursery/letter_cards/c_5_cake.png',
    'candle': 'assets/nursery/letter_cards/c_7_candle.png',
    'cap': 'assets/nursery/letter_cards/c_6_cap.png',
    'car': 'assets/nursery/letter_cards/c_2_car.png',
    'carrot': 'assets/nursery/letter_cards/c_8_carrot.png',
    'cat': 'assets/nursery/letter_cards/c_1_cat.png',
    'cow': 'assets/nursery/letter_cards/c_4_cow.png',
    'cup': 'assets/nursery/letter_cards/c_3_cup.png',
    'deer': 'assets/nursery/letter_cards/d_6_deer.png',
    'dice': 'assets/nursery/letter_cards/d_7_dice.png',
    'dog': 'assets/nursery/letter_cards/d_1_dog.png',
    'doll': 'assets/nursery/letter_cards/d_4_doll.png',
    'donut': 'assets/nursery/letter_cards/d_8_donut.png',
    'door': 'assets/nursery/letter_cards/d_5_door.png',
    'drum': 'assets/nursery/letter_cards/d_3_drum.png',
    'duck': 'assets/nursery/letter_cards/d_2_duck.png',
    'eagle': 'assets/nursery/letter_cards/e_6_eagle.png',
    'ear': 'assets/nursery/letter_cards/e_8_ear.png',
    'earth': 'assets/nursery/letter_cards/e_5_earth.png',
    'egg': 'assets/nursery/letter_cards/e_1_egg.png',
    'elephant': 'assets/nursery/letter_cards/e_2_elephant.png',
    'engine': 'assets/nursery/letter_cards/e_4_engine.png',
    'envelope': 'assets/nursery/letter_cards/e_3_envelope.png',
    'eye': 'assets/nursery/letter_cards/e_7_eye.png',
    'fan': 'assets/nursery/letter_cards/f_8_fan.png',
    'feather': 'assets/nursery/letter_cards/f_6_feather.png',
    'fish': 'assets/nursery/letter_cards/f_1_fish.png',
    'flag': 'assets/nursery/letter_cards/f_5_flag.png',
    'flower': 'assets/nursery/letter_cards/f_3_flower.png',
    'foot': 'assets/nursery/letter_cards/f_7_foot.png',
    'fox': 'assets/nursery/letter_cards/f_4_fox.png',
    'frog': 'assets/nursery/letter_cards/f_2_frog.png',
    'gift': 'assets/nursery/letter_cards/g_3_gift.png',
    'girl': 'assets/nursery/letter_cards/g_4_girl.png',
    'glass': 'assets/nursery/letter_cards/g_5_glass.png',
    'globe': 'assets/nursery/letter_cards/g_7_globe.png',
    'goat': 'assets/nursery/letter_cards/g_1_goat.png',
    'goose': 'assets/nursery/letter_cards/g_8_goose.png',
    'grapes': 'assets/nursery/letter_cards/g_2_grapes.png',
    'guitar': 'assets/nursery/letter_cards/g_6_guitar.png',
    'hammer': 'assets/nursery/letter_cards/h_8_hammer.png',
    'hand': 'assets/nursery/letter_cards/h_5_hand.png',
    'hat': 'assets/nursery/letter_cards/h_1_hat.png',
    'heart': 'assets/nursery/letter_cards/h_6_heart.png',
    'helicopter': 'assets/nursery/letter_cards/h_7_helicopter.png',
    'hen': 'assets/nursery/letter_cards/h_2_hen.png',
    'horse': 'assets/nursery/letter_cards/h_4_horse.png',
    'house': 'assets/nursery/letter_cards/h_3_house.png',
    'ice cream': 'assets/nursery/letter_cards/i_4_ice_cream.png',
    'ice cube': 'assets/nursery/letter_cards/i_7_ice_cube.png',
    'igloo': 'assets/nursery/letter_cards/i_3_igloo.png',
    'iguana': 'assets/nursery/letter_cards/i_6_iguana.png',
    'ink': 'assets/nursery/letter_cards/i_1_ink.png',
    'insect': 'assets/nursery/letter_cards/i_2_insect.png',
    'island': 'assets/nursery/letter_cards/i_5_island.png',
    'ivy': 'assets/nursery/letter_cards/i_8_ivy.png',
    'jacket': 'assets/nursery/letter_cards/j_6_jacket.png',
    'jar': 'assets/nursery/letter_cards/j_4_jar.png',
    'jeans': 'assets/nursery/letter_cards/j_5_jeans.png',
    'jeep': 'assets/nursery/letter_cards/j_7_jeep.png',
    'jet': 'assets/nursery/letter_cards/j_3_jet.png',
    'jewel': 'assets/nursery/letter_cards/j_8_jewel.png',
    'jug': 'assets/nursery/letter_cards/j_1_jug.png',
    'juice': 'assets/nursery/letter_cards/j_2_juice.png',
    'kangaroo': 'assets/nursery/letter_cards/k_4_kangaroo.png',
    'kettle': 'assets/nursery/letter_cards/k_7_kettle.png',
    'key': 'assets/nursery/letter_cards/k_2_key.png',
    'keyboard': 'assets/nursery/letter_cards/k_8_keyboard.png',
    'king': 'assets/nursery/letter_cards/k_3_king.png',
    'kite': 'assets/nursery/letter_cards/k_1_kite.png',
    'kiwi': 'assets/nursery/letter_cards/k_5_kiwi.png',
    'koala': 'assets/nursery/letter_cards/k_6_koala.png',
    'ladder': 'assets/nursery/letter_cards/l_5_ladder.png',
    'ladybug': 'assets/nursery/letter_cards/l_6_ladybug.png',
    'lamp': 'assets/nursery/letter_cards/l_4_lamp.png',
    'leaf': 'assets/nursery/letter_cards/l_2_leaf.png',
    'lemon': 'assets/nursery/letter_cards/l_3_lemon.png',
    'lion': 'assets/nursery/letter_cards/l_1_lion.png',
    'lock': 'assets/nursery/letter_cards/l_7_lock.png',
    'lotus': 'assets/nursery/letter_cards/l_8_lotus.png',
    'mango': 'assets/nursery/letter_cards/m_1_mango.png',
    'milk': 'assets/nursery/letter_cards/m_5_milk.png',
    'mirror': 'assets/nursery/letter_cards/m_6_mirror.png',
    'monkey': 'assets/nursery/letter_cards/m_4_monkey.png',
    'moon': 'assets/nursery/letter_cards/m_2_moon.png',
    'mountain': 'assets/nursery/letter_cards/m_7_mountain.png',
    'mouse': 'assets/nursery/letter_cards/m_3_mouse.png',
    'mug': 'assets/nursery/letter_cards/m_8_mug.png',
    'necklace': 'assets/nursery/letter_cards/n_7_necklace.png',
    'nest': 'assets/nursery/letter_cards/n_1_nest.png',
    'net': 'assets/nursery/letter_cards/n_4_net.png',
    'newspaper': 'assets/nursery/letter_cards/n_5_newspaper.png',
    'nose': 'assets/nursery/letter_cards/n_2_nose.png',
    'notebook': 'assets/nursery/letter_cards/n_8_notebook.png',
    'nurse': 'assets/nursery/letter_cards/n_6_nurse.png',
    'nut': 'assets/nursery/letter_cards/n_3_nut.png',
    'ocean': 'assets/nursery/letter_cards/o_7_ocean.png',
    'octopus': 'assets/nursery/letter_cards/o_3_octopus.png',
    'olive': 'assets/nursery/letter_cards/o_6_olive.png',
    'onion': 'assets/nursery/letter_cards/o_5_onion.png',
    'orange': 'assets/nursery/letter_cards/o_1_orange.png',
    'ostrich': 'assets/nursery/letter_cards/o_8_ostrich.png',
    'owl': 'assets/nursery/letter_cards/o_4_owl.png',
    'ox': 'assets/nursery/letter_cards/o_2_ox.png',
    'panda': 'assets/nursery/letter_cards/p_6_panda.png',
    'parrot': 'assets/nursery/letter_cards/p_4_parrot.png',
    'peacock': 'assets/nursery/letter_cards/p_7_peacock.png',
    'pear': 'assets/nursery/letter_cards/p_3_pear.png',
    'pen': 'assets/nursery/letter_cards/p_1_pen.png',
    'pig': 'assets/nursery/letter_cards/p_2_pig.png',
    'pizza': 'assets/nursery/letter_cards/p_5_pizza.png',
    'pumpkin': 'assets/nursery/letter_cards/p_8_pumpkin.png',
    'quail': 'assets/nursery/letter_cards/q_4_quail.png',
    'quarter': 'assets/nursery/letter_cards/q_6_quarter.png',
    'queen': 'assets/nursery/letter_cards/q_1_queen.png',
    'question': 'assets/nursery/letter_cards/q_2_question.png',
    'quiet': 'assets/nursery/letter_cards/q_8_quiet.png',
    'quill': 'assets/nursery/letter_cards/q_5_quill.png',
    'quilt': 'assets/nursery/letter_cards/q_3_quilt.png',
    'quiver': 'assets/nursery/letter_cards/q_7_quiver.png',
    'rabbit': 'assets/nursery/letter_cards/r_1_rabbit.png',
    'rain': 'assets/nursery/letter_cards/r_3_rain.png',
    'rainbow': 'assets/nursery/letter_cards/r_7_rainbow.png',
    'ring': 'assets/nursery/letter_cards/r_4_ring.png',
    'robot': 'assets/nursery/letter_cards/r_5_robot.png',
    'rocket': 'assets/nursery/letter_cards/r_6_rocket.png',
    'rooster': 'assets/nursery/letter_cards/r_8_rooster.png',
    'rose': 'assets/nursery/letter_cards/r_2_rose.png',
    'scissors': 'assets/nursery/letter_cards/s_8_scissors.png',
    'ship': 'assets/nursery/letter_cards/s_4_ship.png',
    'six': 'assets/nursery/letter_cards/x_7_six.png',
    'snake': 'assets/nursery/letter_cards/s_3_snake.png',
    'socks': 'assets/nursery/letter_cards/s_6_socks.png',
    'spoon': 'assets/nursery/letter_cards/s_5_spoon.png',
    'star': 'assets/nursery/letter_cards/s_2_star.png',
    'strawberry': 'assets/nursery/letter_cards/s_7_strawberry.png',
    'sun': 'assets/nursery/letter_cards/s_1_sun.png',
    'taxi': 'assets/nursery/letter_cards/x_8_taxi.png',
    'teddy': 'assets/nursery/letter_cards/t_7_teddy.png',
    'tiger': 'assets/nursery/letter_cards/t_1_tiger.png',
    'tomato': 'assets/nursery/letter_cards/t_4_tomato.png',
    'toothbrush': 'assets/nursery/letter_cards/t_5_toothbrush.png',
    'train': 'assets/nursery/letter_cards/t_3_train.png',
    'tree': 'assets/nursery/letter_cards/t_2_tree.png',
    'truck': 'assets/nursery/letter_cards/t_8_truck.png',
    'turtle': 'assets/nursery/letter_cards/t_6_turtle.png',
    'ukulele': 'assets/nursery/letter_cards/u_8_ukulele.png',
    'umbrella': 'assets/nursery/letter_cards/u_1_umbrella.png',
    'under': 'assets/nursery/letter_cards/u_3_under.png',
    'unicorn': 'assets/nursery/letter_cards/u_4_unicorn.png',
    'uniform': 'assets/nursery/letter_cards/u_5_uniform.png',
    'up': 'assets/nursery/letter_cards/u_2_up.png',
    'urn': 'assets/nursery/letter_cards/u_7_urn.png',
    'utensils': 'assets/nursery/letter_cards/u_6_utensils.png',
    'vacuum': 'assets/nursery/letter_cards/v_7_vacuum.png',
    'van': 'assets/nursery/letter_cards/v_1_van.png',
    'vase': 'assets/nursery/letter_cards/v_4_vase.png',
    'vegetable': 'assets/nursery/letter_cards/v_3_vegetable.png',
    'vest': 'assets/nursery/letter_cards/v_6_vest.png',
    'violin': 'assets/nursery/letter_cards/v_2_violin.png',
    'volcano': 'assets/nursery/letter_cards/v_5_volcano.png',
    'vulture': 'assets/nursery/letter_cards/v_8_vulture.png',
    'wagon': 'assets/nursery/letter_cards/w_8_wagon.png',
    'watch': 'assets/nursery/letter_cards/w_1_watch.png',
    'water': 'assets/nursery/letter_cards/w_2_water.png',
    'watermelon': 'assets/nursery/letter_cards/w_5_watermelon.png',
    'wax': 'assets/nursery/letter_cards/x_6_wax.png',
    'whale': 'assets/nursery/letter_cards/w_3_whale.png',
    'wheel': 'assets/nursery/letter_cards/w_6_wheel.png',
    'window': 'assets/nursery/letter_cards/w_4_window.png',
    'worm': 'assets/nursery/letter_cards/w_7_worm.png',
    'x-ray': 'assets/nursery/letter_cards/x_1_x_ray.png',
    'xylophone': 'assets/nursery/letter_cards/x_2_xylophone.png',
    'yacht': 'assets/nursery/letter_cards/y_4_yacht.png',
    'yak': 'assets/nursery/letter_cards/y_1_yak.png',
    'yam': 'assets/nursery/letter_cards/y_8_yam.png',
    'yarn': 'assets/nursery/letter_cards/y_5_yarn.png',
    'yellow': 'assets/nursery/letter_cards/y_2_yellow.png',
    'yo-yo': 'assets/nursery/letter_cards/y_3_yo_yo.png',
    'yogurt': 'assets/nursery/letter_cards/y_6_yogurt.png',
    'yolk': 'assets/nursery/letter_cards/y_7_yolk.png',
    'zebra': 'assets/nursery/letter_cards/z_1_zebra.png',
    'zeppelin': 'assets/nursery/letter_cards/z_7_zeppelin.png',
    'zero': 'assets/nursery/letter_cards/z_2_zero.png',
    'zigzag': 'assets/nursery/letter_cards/z_6_zigzag.png',
    'zip': 'assets/nursery/letter_cards/z_4_zip.png',
    'zoo': 'assets/nursery/letter_cards/z_3_zoo.png',
    'zoom': 'assets/nursery/letter_cards/z_8_zoom.png',
    'zucchini': 'assets/nursery/letter_cards/z_5_zucchini.png',
  };

  static const Map<String, String> _aliases = <String, String>{
    'airplane': 'aeroplane',
    'plane': 'aeroplane',
    'yo yo': 'yo-yo',
    'yoyo': 'yo-yo',
  };

  static int get illustrationCount => _assetByWord.length;

  static Iterable<String> get authoredWords => _assetByWord.keys;

  static String? assetForLabel(String value) {
    final normalized = _normalize(value);
    if (normalized.isEmpty) return null;
    final direct = _assetByWord[normalized];
    if (direct != null) return direct;
    final alias = _aliases[normalized];
    if (alias != null) return _assetByWord[alias];
    final withoutCount = normalized.replaceFirst(RegExp(r'^\d+\s+'), '');
    final singular = _singularize(withoutCount);
    return _assetByWord[withoutCount] ?? _assetByWord[singular];
  }

  static String _normalize(String value) => value
      .trim()
      .toLowerCase()
      .replaceAll(RegExp(r'[^a-z0-9-]+'), ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();

  static String _singularize(String value) {
    if (value.endsWith('ies') && value.length > 3) {
      return '${value.substring(0, value.length - 3)}y';
    }
    if (value.endsWith('es') && value.length > 2) {
      final candidate = value.substring(0, value.length - 2);
      if (_assetByWord.containsKey(candidate)) return candidate;
    }
    if (value.endsWith('s') && value.length > 1) {
      return value.substring(0, value.length - 1);
    }
    return value;
  }
}
